const images = {
    breadcrumb: require("../img/breadcrumb.jpg"),
    language: require("../img/language.png"),
    logo: require("../img/logo.png"),
    feature1: require("../img/featured/feature-1.jpg"),
    feature2: require("../img/featured/feature-2.jpg"),
    feature3: require("../img/featured/feature-3.jpg"),
    feature4: require("../img/featured/feature-4.jpg"),
    feature5: require("../img/featured/feature-5.jpg"),
    feature6: require("../img/featured/feature-6.jpg"),
    feature7: require("../img/featured/feature-7.jpg"),
    feature8: require("../img/featured/feature-8.jpg"),
    blog1: require("../img/blog/blog-1.jpg"),
    blog2: require("../img/blog/blog-2.jpg"),
    blog3: require("../img/blog/blog-3.jpg"),
    blog4: require("../img/blog/blog-4.jpg"),
    blog5: require("../img/blog/blog-5.jpg"),
    blog6: require("../img/blog/blog-6.jpg"),
    author: require("../img/blog/details/details-author.jpg"),
    pic: require("../img/blog/details/details-pic.jpg"),
    hero: require("../img/blog/details/details-hero.jpg"),
    sr1: require("../img/blog/sidebar/sr-1.jpg"),
    sr2: require("../img/blog/sidebar/sr-2.jpg"),
    sr3: require("../img/blog/sidebar/sr-3.jpg"),
    cart1: require("../img/cart/cart-1.jpg"),
    cart2: require("../img/cart/cart-1.jpg"),
    cart3: require("../img/cart/cart-1.jpg"),
    cat1: require("../img/categories/cat-1.jpg"),
    cat2: require("../img/categories/cat-2.jpg"),
    cat3: require("../img/categories/cat-3.jpg"),
    cat4: require("../img/categories/cat-4.jpg"),
    cat5: require("../img/categories/cat-5.jpg"),
    herobanner: require("../img/hero/banner.jpg"),
    lp1: require("../img/latestProduct/lp-1.jpg"),
    lp2: require("../img/latestProduct/lp-2.jpg"),
    lp3: require("../img/latestProduct/lp-3.jpg"),
    product1: require("../img/product/product-1.jpg"),
    product2: require("../img/product/product-2.jpg"),
    product3: require("../img/product/product-3.jpg"),
    product4: require("../img/product/product-4.jpg"),
    product5: require("../img/product/product-5.jpg"),
    product6: require("../img/product/product-6.jpg"),
    product7: require("../img/product/product-7.jpg"),
    product8: require("../img/product/product-8.jpg"),
    product9: require("../img/product/product-9.jpg"),
    product10: require("../img/product/product-10.jpg"),
    product11: require("../img/product/product-11.jpg"),
    product12: require("../img/product/product-12.jpg"),
    productDetails1: require("../img/product/details/product-details-1.jpg"),
    productDetails2: require("../img/product/details/product-details-2.jpg"),
    productDetails3: require("../img/product/details/product-details-3.jpg"),
    productDetails4: require("../img/product/details/product-details-4.jpg"),
    productDetails5: require("../img/product/details/product-details-5.jpg"),
    thumb1: require("../img/product/details/thumb-1.jpg"),
    thumb2: require("../img/product/details/thumb-2.jpg"),
    thumb3: require("../img/product/details/thumb-3.jpg"),
    thumb4: require("../img/product/details/thumb-4.jpg"),
    pd1: require("../img/product/discount/pd-1.jpg"),
    pd2: require("../img/product/discount/pd-2.jpg"),
    pd3: require("../img/product/discount/pd-3.jpg"),
    pd4: require("../img/product/discount/pd-4.jpg"),
    pd5: require("../img/product/discount/pd-5.jpg"),
    pd6: require("../img/product/discount/pd-6.jpg"),
    ban1: require("../img/banner/banner-1.jpg"),
    ban2: require("../img/banner/banner-2.jpg"),

    

}
  
  export default images;